In [5]:
import numpy as np

In [7]:
stock_day_rise = np.random.normal(0, 1, (500, 504)) # 均值，标准差，（行，列）

In [8]:
# 获取前四天的股票， 对前四天进行操作
temp =stock_day_rise[:4, :4].copy()

In [10]:
temp

array([[-1.43555191, -1.45800187, -1.84308482, -2.48731355],
       [-1.02288664, -0.29870782, -1.19091728,  1.76451333],
       [-0.79984572, -0.67094547, -0.48619663,  0.15193851],
       [-0.768814  ,  0.17621697,  1.524756  ,  1.11904686]])

In [11]:
temp > 0.5

array([[False, False, False, False],
       [False, False, False,  True],
       [False, False, False, False],
       [False, False,  True,  True]])

In [12]:
# 通用函数判断
np.all(temp>0.5) # 对所有函数进行判断

False

In [14]:
# 对于大于0.5的值变为1， 否则为0
np.where(temp>0.5, 1, 0)

array([[0, 0, 0, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 1, 1]])

In [16]:
# 且条件，其他类似, 或，非， 异或
np.where(np.logical_and(temp>0.5, temp<1), 1, 0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])