In [1]:
import numpy as np

In [2]:
stock_day_rise = np.random.normal(0, 1, (500, 504)) # 均值，标准差，（行，列）

In [4]:
# 获取前四天的股票， 对前四天进行操作
temp =stock_day_rise[:4, :4].copy()

In [5]:
temp

array([[ 1.77792025, -0.20931722,  1.48062431, -0.13808363],
       [ 1.55237353,  0.12838009,  1.31741929,  0.70861924],
       [-0.09184806, -0.66893534,  1.49137578,  0.34925636],
       [-0.23763893,  1.95774205, -2.24414644,  0.69611567]])

In [10]:
print(np.max(temp, axis=1)) #每行的最大值,axis=0为列
print(np.min(temp, axis=1)) #每行的最小值
print(np.std(temp, axis=1)) #每行的标准差
print(np.var(temp, axis=1)) #每行的方差
print(np.mean(temp, axis=1)) #每行的均值

[1.77792025 1.55237353 1.49137578 1.95774205]
[-0.20931722  0.12838009 -0.66893534 -2.24414644]
[0.90794275 0.554302   0.79223954 1.5331825 ]
[0.82436003 0.30725071 0.62764349 2.35064857]
[0.72778593 0.92669804 0.26996219 0.04301809]


In [11]:
# 得到相应位置
print(np.argmax(temp, axis=1)) #每行的最大值位置,axis=0为列

[0 0 2 1]
