In [54]:
import numpy as np

In [55]:
arr = np.array([1,2,3,4])

In [56]:
arr+1

array([2, 3, 4, 5])

In [59]:
# 数组与数组之间的运算
# 广播机制
a = np.array([[4,5,6],[7,8,9]])
a

array([[4, 5, 6],
       [7, 8, 9]])

In [60]:
b = np.array([[2,10], [2, 15],[2,1]])
b

array([[ 2, 10],
       [ 2, 15],
       [ 2,  1]])

要想进行矩阵乘法需要使用 **np.dot()** ；

直接a*b被认为是numpy中元素一一对应的方式进行计算的，其中隐式的将一个向量复制到每一行而生成一个矩阵。
这种隐式地复制向量到很多位置的方式，被称为 **广播（broadcast）**。

In [62]:

# a * b  #element-wise

np.dot(a,b)

array([[ 30, 121],
       [ 48, 199]])

要想进行广播需要满足三个条件：

1. 当两个矩阵shape相同的时候，直接进行计算。

2. 当两个矩阵shape不相同的时候，当且仅当不相同的两个轴的其中一个长度为1的时候，就会沿着这个轴，将其他方向的值复制

扩展为所需大小的矩阵。

3. 输出的数组的大小是输入数组的各个轴的最大值。


In [ ]:
score = np.array([[80,86],
[82,80],
[85,78],
[90,90],
[86,82],
[82,90],
[78,80],
[92,94]])

In [ ]:
percent = np.array([[0.3, 0.7]])

In [ ]:
score * percent

array([[24. , 60.2],
       [24.6, 56. ],
       [25.5, 54.6],
       [27. , 63. ],
       [25.8, 57.4],
       [24.6, 63. ],
       [23.4, 56. ],
       [27.6, 65.8]])

In [ ]:
# 矩阵，特殊在运算机制
np.mat(score)

matrix([[80, 86],
        [82, 80],
        [85, 78],
        [90, 90],
        [86, 82],
        [82, 90],
        [78, 80],
        [92, 94]])

In [ ]:
c = np.array([[0.3], [0.7]])

In [ ]:
np.mat(c)

matrix([[0.3],
        [0.7]])

In [ ]:
# 矩阵运算
# (8, 2) * (2, 1) = (8, 1)
# 矩阵乘法
np.matmul(score, c)

array([[84.2],
       [80.6],
       [80.1],
       [90. ],
       [83.2],
       [87.6],
       [79.4],
       [93.4]])

In [ ]:
stock_day_rise = np.random.normal(0, 1, [500, 504])

In [ ]:
stock_day_rise.shape

(500, 504)

In [ ]:
stock1 = stock_day_rise[:10, :100]

In [ ]:
stock2 = stock_day_rise[10: 20, :100]

In [ ]:
stock2

array([[-6.42946537e-01, -4.32004390e-01, -3.59174176e-01,
         1.46195215e+00, -2.66096774e+00,  1.48385220e+00,
         3.08942809e-01, -7.33684685e-01,  3.74779499e-01,
         1.33574646e+00,  2.69323801e-01, -8.21038581e-01,
         2.47343465e+00, -4.87143241e-02, -1.19716350e+00,
        -7.05927144e-02, -7.71815306e-01, -1.70142201e-01,
        -6.66223655e-01,  1.59215432e-01,  3.40838737e-01,
         1.39331375e+00, -2.10939636e+00,  3.19988677e-01,
         5.51126562e-01, -1.93544640e-01,  8.44795138e-01,
        -8.01243166e-01, -1.37868511e-01,  4.74719185e-01,
        -1.37849021e+00,  1.31573022e-01, -5.70385352e-01,
        -5.82089328e-01, -1.87195201e-01, -3.17696449e-01,
         1.89603459e+00, -1.23750062e+00,  6.79000610e-01,
         9.24119711e-01,  1.00622377e+00,  1.07929105e-01,
         5.72047799e-01,  1.07993718e+00,  2.78705842e-01,
        -4.35400256e-01, -1.04347442e+00,  2.02446591e-02,
         1.11532370e+00,  2.29463534e+00, -1.00144935e+0

In [ ]:
# 合并
# axis: 0按照数组的行的方向拼接在一起
# axis: 1按照数组的列的方向拼接在一起

all_ = np.concatenate([stock1, stock2], axis=0)

In [ ]:
all_

array([[-0.70309963, -1.27624375, -2.02276294, ...,  1.42209578,
         1.0719141 , -1.33430294],
       [ 0.24767652, -0.79994649,  0.3109115 , ..., -0.41916317,
         0.23572732,  1.33225981],
       [-0.34271007, -1.65476695, -0.01375825, ..., -0.84406621,
        -1.13447403,  1.79564031],
       ...,
       [-0.32520439,  0.44367219, -0.02093327, ..., -0.28055328,
        -0.16636438,  2.24052651],
       [ 0.37882814,  0.53022027, -2.57873511, ...,  1.44809276,
        -1.38570035, -0.43108605],
       [ 0.00325989,  0.57035532, -2.45496258, ...,  0.64513761,
         0.65874489, -2.82010352]])

hstack  列拼接  axis: 1

vstack  行拼接  axis: 0

In [ ]:
# 分割
np.split(all_, 20, axis=0)

[array([[-7.03099628e-01, -1.27624375e+00, -2.02276294e+00,
          1.61710273e-03,  5.48411067e-01,  4.47589647e-01,
          6.32674107e-01, -7.16499982e-02, -1.13850264e+00,
         -1.35900828e+00,  2.04678452e+00, -1.31442836e+00,
          4.02967676e-01,  3.75139709e-01, -2.05965613e+00,
          2.51651404e-01, -7.69938188e-02, -1.45493098e-03,
         -2.91176480e+00,  4.61522384e-01, -1.62204344e-01,
         -7.93821160e-03,  8.73678091e-01, -1.49985794e+00,
         -5.14216318e-01, -5.95137937e-01, -3.05011766e-01,
         -3.14715978e-01,  3.39130576e-01, -4.25032424e-01,
         -8.11649112e-01, -3.93347932e-01, -6.87704255e-01,
         -8.54347913e-01,  1.70569533e+00, -7.60003465e-01,
          3.40032000e-01, -8.74929910e-01, -4.27941462e-01,
          5.86308651e-01, -3.89629378e-01,  7.21785226e-02,
          1.60371501e+00,  6.79250726e-01, -4.50772105e-01,
         -3.19967733e-01,  1.53863283e+00, -1.92666966e+00,
         -7.34813265e-01, -1.11460915e+0

In [ ]:
# 读取文件
np.genfromtxt('test.csv', delimiter=',')

OSError: test.csv not found.

In [ ]:
# 读取文件，若类型不匹配，则为 nan
type(np.nan)

float

In [ ]:
e = 2.73

In [ ]:
1/e

0.3663003663003663

In [ ]:
np.exp(2)

7.38905609893065

In [ ]:
1 / np.exp(2)

0.1353352832366127

In [ ]:
1 / (1 + 1/np.exp(2))

0.8807970779778823

In [ ]:
np.exp(2)

7.38905609893065

In [ ]:
m = np.array([1,2,3])

In [ ]:
1 / (1 + 1/np.exp(m))

array([0.73105858, 0.88079708, 0.95257413])